
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: indecovietnamdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

  backend:
    build: 
      context: ../indeco-be
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ../indeco-be/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  client:
    build: 
      context: ../indeco-client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../indeco-client/.env

  admin:
    build: 
      context: ../indeco-admin
      dockerfile: Dockerfile
    container_name: admin
    restart: always
    ports:
      - "3001:80"
    env_file:
      - ../indeco-admin/.env.production

  redis-server:
    image: redis:8-alpine
    container_name: redis-server
    restart: always
    ports:
      - "6380:6379"   # host 6380 map tới container 6379, tránh trùng cổng nếu Redis online cũng dùng 6379
    volumes:
      - redisdata:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - client
      - admin
      - backend
    networks:
      - indeco_network
      
networks:
  indeco_network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
